"""initial schema

Revision ID: 266b19746398
Revises: 
Create Date: 2026-09-10 10:11:43.062771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '266b19746398'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msp_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('base_fee_monthly', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('price_per_kwh_ac', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('price_per_kwh_dc', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('roaming_price_per_kwh', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('covered_operator_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocm_operator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=False)
    op.create_index(op.f('ix_operators_ocm_operator_id'), 'operators', ['ocm_operator_id'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocm_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('max_power_kw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('usage_type', sa.String(length=64), nullable=True),
    sa.Column('is_ac', sa.Boolean(), nullable=False),
    sa.Column('is_dc', sa.Boolean(), nullable=False),
    sa.Column('drive_through', sa.Boolean(), nullable=False),
    sa.Column('caravan_friendly', sa.Boolean(), nullable=False),
    sa.Column('trailer_friendly', sa.Boolean(), nullable=False),
    sa.Column('hgv_friendly', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_ocm_id'), 'stations', ['ocm_id'], unique=True)
    op.create_index(op.f('ix_stations_operator_id'), 'stations', ['operator_id'], unique=False)
    # Note: the GIST spatial index on stations.geom (idx_stations_geom) is
    # created automatically by GeoAlchemy2 via a DDL event when the table is
    # created (Geometry(..., spatial_index=True)), so we don't create it
    # explicitly here to avoid a duplicate-index error.
    # Note: op.drop_table('spatial_ref_sys') intentionally omitted — this is
    # PostGIS's own system table, not managed by our application metadata.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_operator_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_ocm_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_operators_ocm_operator_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    op.drop_table('msp_tariffs')
    # ### end Alembic commands ###
